name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - main # 確保這裡的分支名稱與你的主分支一致

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0' # 這裡指定了你希望使用的 Ruby 版本
          bundler-cache: true

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./_site
